### ISSUE TITLE
Upstream...

### ISSUE THREAD

**Issue by jamtur01** [avishai-ish-shalom/riemann-flapjack-output#1]
Any chance you're planning to submit this upstream? Seems like a worthy addition for Riemann core.

Thanks for writing this - awesomely useful!

**Comment by avishai-ish-shalom** [comment]
The plugin needs more work - e.g. tests and real world feedback from users. Once that's done I will certainly push for a merge upstream.

**Comment by jamtur01** [comment]
I can say I'm pretty happy with the real world workings if that helps. Finding it highly useful.

**Comment by avishai-ish-shalom** [comment]
@aphyr would you be interested in having this in riemann? does the code need more work?

**Comment by aphyr** [comment]
Naw, I actually want to fold as much stuff out into third-party libraries as possible. This is great! :)
